name: CI


on:
  pull_request:
    branches: [ 'master', 'main' ]

  push:
    branches: [ 'master', 'main' ]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8 space_game/

      - name: Run mypy
        run: poetry run mypy space_game/
